server:
  port: 9761
# 安全认证的配置  
#security:  
  #basic:  
    #enabled: true  
  #user:  
    #name: csrk  # 用户名  
    #password: csrk123,./   # 用户密码  
eureka:
  instance:
    hostname: 0.0.0.0
    prefer-ip-address: true
    ip-address: 106.13.125.118
    lease-expiration-duration-in-seconds: 30
    lease-renewal-interval-in-seconds: 5
  client:
    #由于该应用为注册中心,所以设置为false,代表不向注册中心注册自己
    registerWithEureka: false
    #由于注册中心的职责就是维护服务实例,它并不需要去检索服务,所以也设置为false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/